# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_split_on_all 1'] = [
    [
        'Cuénta',
        'contar',
        'VERB',
        'VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin',
        True,
        'suffix_melo',
        'suffix',
        'Cuenta',
        2
    ],
    [
        'me',
        'me',
        'PRON',
        'PRON__Number=Sing|Person=1|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'lo',
        'el',
        'DET',
        'DET__Definite=Def|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'bien',
        'bien',
        'ADV',
        'ADV___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'y',
        'y',
        'CONJ',
        'CCONJ___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'di',
        'decir',
        'VERB',
        'VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin',
        True,
        'suffix_lo',
        'suffix',
        'di',
        1
    ],
    [
        'lo',
        'el',
        'DET',
        'DET__Definite=Def|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'claro',
        'claro',
        'ADJ',
        'ADJ__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        ',',
        ',',
        'PUNCT',
        'PUNCT__PunctType=Comm',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'no',
        'no',
        'ADV',
        'ADV__Polarity=Neg',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'me',
        'me',
        'PRON',
        'PRON__Number=Sing|Person=1',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'des',
        'dar',
        'ADP',
        'ADP__AdpType=Prep',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'un',
        'uno',
        'DET',
        'DET__Definite=Ind|Gender=Masc|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'caramelo',
        'caramelo',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_all 2'] = [
    [
        'Yo',
        'Yo',
        'PRON',
        'PRON__Case=Nom|Number=Sing|Person=1|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'misma',
        'mismo',
        'ADV',
        'ADV___',
        True,
        'suffix_mente',
        'suffix',
        'misma',
        1
    ],
    [
        'mente',
        'mente',
        'NOUN',
        'NOUN__Gender=Fem|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'podría',
        'poder',
        'AUX',
        'AUX__Mood=Cnd|Number=Sing|Person=3|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hacér',
        'hacer',
        'VERB',
        'VERB__VerbForm=Inf',
        True,
        'suffix_selo',
        'suffix',
        'hacer',
        2
    ],
    [
        'se',
        'despacio',
        'ADV',
        'ADV___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'lo',
        'el',
        'DET',
        'DET__Definite=Def|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'despac',
        'despacio',
        'ADV',
        'ADV___',
        True,
        'suffix_ito',
        'suffix',
        'despacio',
        1
    ],
    [
        'ito',
        'ito',
        'ADJ',
        'ADJ__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_all 3'] = [
    [
        'Soy',
        'Soy',
        'AUX',
        'AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hispano',
        'hispano',
        'ADJ',
        'X',
        True,
        'prefix_hispano',
        'prefix',
        'americano',
        1
    ],
    [
        'americano',
        'americano',
        'ADJ',
        'ADJ__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'y',
        'y',
        'CONJ',
        'CCONJ___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'antirrevolucionario',
        'antirrevolucionario',
        'ADJ',
        'ADJ__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_all 4'] = [
    [
        'Di',
        'decir',
        'VERB',
        'VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin',
        True,
        'suffix_me',
        'suffix',
        'Di',
        1
    ],
    [
        'me',
        'me',
        'PRON',
        'PRON__Number=Sing|Person=1|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'el',
        'el',
        'DET',
        'DET__Definite=Def|Gender=Masc|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'número',
        'número',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'de',
        'de',
        'ADP',
        'ADP__AdpType=Prep',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'teléfono',
        'teléfono',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_all 5'] = [
    [
        'Hay',
        'Hay',
        'AUX',
        'AUX__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'que',
        'que',
        'SCONJ',
        'SCONJ___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hacér',
        'hacer',
        'VERB',
        'VERB__VerbForm=Inf',
        True,
        'suffix_selo',
        'suffix',
        'hacer',
        2
    ],
    [
        'se',
        'se',
        'PRON',
        'PRON__Person=3|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'lo',
        'el',
        'PRON',
        'PRON__Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'todo',
        'todo',
        'PRON',
        'PRON__Gender=Masc|Number=Sing|PronType=Ind',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_verbs 1'] = [
    [
        'Cuénta',
        'contar',
        'VERB',
        'VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin',
        True,
        'suffix_melo',
        'suffix',
        'Cuenta',
        2
    ],
    [
        'me',
        'me',
        'PRON',
        'PRON__Number=Sing|Person=1|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'lo',
        'el',
        'DET',
        'DET__Definite=Def|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'bien',
        'bien',
        'ADV',
        'ADV___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'y',
        'y',
        'CONJ',
        'CCONJ___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'di',
        'decir',
        'VERB',
        'VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin',
        True,
        'suffix_lo',
        'suffix',
        'di',
        1
    ],
    [
        'lo',
        'el',
        'DET',
        'DET__Definite=Def|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'claro',
        'claro',
        'ADJ',
        'ADJ__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        ',',
        ',',
        'PUNCT',
        'PUNCT__PunctType=Comm',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'no',
        'no',
        'ADV',
        'ADV__Polarity=Neg',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'me',
        'me',
        'PRON',
        'PRON__Number=Sing|Person=1',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'des',
        'dar',
        'ADP',
        'ADP__AdpType=Prep',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'un',
        'uno',
        'DET',
        'DET__Definite=Ind|Gender=Masc|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'caramelo',
        'caramelo',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_verbs 2'] = [
    [
        'Yo',
        'Yo',
        'PRON',
        'PRON__Case=Nom|Number=Sing|Person=1|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'mismamente',
        'mismo',
        'ADV',
        'ADV___',
        True,
        'suffix_mente',
        'suffix',
        'misma',
        1
    ],
    [
        'podría',
        'poder',
        'AUX',
        'AUX__Mood=Cnd|Number=Sing|Person=3|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hacér',
        'hacer',
        'VERB',
        'VERB__VerbForm=Inf',
        True,
        'suffix_selo',
        'suffix',
        'hacer',
        2
    ],
    [
        'se',
        'despacio',
        'ADV',
        'ADV___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'lo',
        'el',
        'DET',
        'DET__Definite=Def|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'despacito',
        'despacio',
        'ADV',
        'ADV___',
        True,
        'suffix_ito',
        'suffix',
        'despacio',
        1
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_verbs 3'] = [
    [
        'Soy',
        'Soy',
        'AUX',
        'AUX__Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hispanoamericano',
        'hispanoamericano',
        'ADJ',
        'X',
        True,
        'prefix_hispano',
        'prefix',
        'americano',
        1
    ],
    [
        'y',
        'y',
        'CONJ',
        'CCONJ___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'antirrevolucionario',
        'antirrevolucionario',
        'ADJ',
        'ADJ__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_verbs 4'] = [
    [
        'Di',
        'decir',
        'VERB',
        'VERB__Mood=Imp|Number=Sing|Person=2|VerbForm=Fin',
        True,
        'suffix_me',
        'suffix',
        'Di',
        1
    ],
    [
        'me',
        'me',
        'PRON',
        'PRON__Number=Sing|Person=1|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'el',
        'el',
        'DET',
        'DET__Definite=Def|Gender=Masc|Number=Sing|PronType=Art',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'número',
        'número',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'de',
        'de',
        'ADP',
        'ADP__AdpType=Prep',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'teléfono',
        'teléfono',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_split_on_verbs 5'] = [
    [
        'Hay',
        'Hay',
        'AUX',
        'AUX__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'que',
        'que',
        'SCONJ',
        'SCONJ___',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hacér',
        'hacer',
        'VERB',
        'VERB__VerbForm=Inf',
        True,
        'suffix_selo',
        'suffix',
        'hacer',
        2
    ],
    [
        'se',
        'se',
        'PRON',
        'PRON__Person=3|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'lo',
        'el',
        'PRON',
        'PRON__Case=Acc|Gender=Masc|Number=Sing|Person=3|PronType=Prs',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'todo',
        'todo',
        'PRON',
        'PRON__Gender=Masc|Number=Sing|PronType=Ind',
        False,
        None,
        None,
        None,
        0
    ],
    [
        '.',
        '.',
        'PUNCT',
        'PUNCT__PunctType=Peri',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_accent_exceptions 1'] = [
    [
        'demente',
        'demente',
        'ADJ',
        'ADJ__Number=Sing',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_accent_exceptions 2'] = [
    [
        'Ese',
        'Ese',
        'DET',
        'DET__Gender=Masc|Number=Sing|PronType=Dem',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'hombre',
        'hombre',
        'NOUN',
        'NOUN__Gender=Masc|Number=Sing',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'está',
        'estar',
        'AUX',
        'AUX__Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin',
        False,
        None,
        None,
        None,
        0
    ],
    [
        'demente',
        'demente',
        'ADJ',
        'ADJ__Number=Sing',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_accent_exceptions 3'] = [
    [
        'automáticamente',
        'automático',
        'ADV',
        'ADV___',
        True,
        'suffix_mente',
        'suffix',
        'automática',
        1
    ]
]

snapshots['test_accent_exceptions 4'] = [
    [
        'mágicamente',
        'mágicamente',
        'ADV',
        'ADV___',
        False,
        None,
        None,
        None,
        0
    ]
]

snapshots['test_accent_exceptions 5'] = [
    [
        'antirrevolucionariamente',
        'antirrevolucionario',
        'ADV',
        'ADV___',
        True,
        'suffix_mente',
        'suffix',
        'antirrevolucionaria',
        1
    ]
]
